//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTIPriceSalesPush.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("posdataq")]
        public string TotalsMsgQName {
            get {
                return ((string)(this["TotalsMsgQName"]));
            }
            set {
                this["TotalsMsgQName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=mytankinfo;AccountKey=+svfiSG9yOt8OuYF" +
            "lZfkhz97n0dlPsCXLdKyIEZpAX32yn9JRhR77P5QdDnCv7ClPVPB/SdrNLQIoBAQJmy4yw==;Endpoin" +
            "tSuffix=core.windows.net")]
        public string PosDataQConnection {
            get {
                return ((string)(this["PosDataQConnection"]));
            }
            set {
                this["PosDataQConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pospricemsgq")]
        public string PriceMsgQName {
            get {
                return ((string)(this["PriceMsgQName"]));
            }
            set {
                this["PriceMsgQName"] = value;
            }
        }
    }
}
